services:
  backend:
    image: realestate-backend
    container_name: realestate-backend
    build: .
    ports:
      - "3013:8080"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/realestate_db
      SPRING_DATASOURCE_USERNAME: realestate_user
      SPRING_DATASOURCE_PASSWORD: realestate_password
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: realestate-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: realestate_db
      POSTGRES_USER: realestate_user
      POSTGRES_PASSWORD: realestate_password
    volumes:
      - realestate-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  realestate-pgdata:



