version: "3.8"

services:
  backend:
    image: realestate_db
    container_name: realestate_db
    build: .
    ports:
      - "3012:8080"   # ana nginx ile uyumlu
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/realestate_db
      SPRING_DATASOURCE_USERNAME: realestate_user
      SPRING_DATASOURCE_PASSWORD: realestate_password
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: realestate_db
    ports:
      - "5435:5432"   # host port 5433 → container 5432
    environment:
      POSTGRES_DB: realestate-db
      POSTGRES_USER: realestate_user
      POSTGRES_PASSWORD: realestate_password
    volumes:
      - realestate-pgdata:/var/lib/postgresql/data   # kalıcı veri

volumes:
  realestate-pgdata:



