spring.application.name=backend

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/realestate_db
spring.datasource.username=realestate_user
spring.datasource.password=realestate_password
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server configuration
spring.main.allow-bean-definition-overriding=true
server.address=0.0.0.0

# JWT Configuration
jwt.secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
jwt.expiration=3600000

# Mail Configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test@test.com
spring.mail.password=test
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
frontend.url=http://localhost:3000

file.upload-dir=uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB